TDL 16384 check best practices and TDL 16465 Make replication key with automatic inclusion
singer-io/tap-activecampaign pull request #11
Opened 2021-12-08 06:12 UTC by prijendev

# Description of change
- Added following below integration tests
- Start Date Test
- Pagination Test
- Automatic Fields Test
- All Fields Test
- Bookmark Test
- Discovery Test

# Manual QA steps
 - 
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2022-01-05 10:00 UTC, prijendev commented on tap_activecampaign/transform.py
> +    fix_records(converted_json)
Fixed pylint error assignment-from-no-return. ([Reference](https://app.circleci.com/pipelines/github/singer-io/tap-activecampaign/551/workflows/e896a4c7-a0aa-4e56-9dd1-e1eb312518bb/jobs/555))

2022-01-11 16:01 UTC, umangagrawal-crest commented on tests/test_discover.py
> +                # Verify ensure the caatalog is found for a given stream
```suggestion
                # Verify the catalog is found for a given stream
```

2022-01-11 16:29 UTC, umangagrawal-crest requested changes

2022-01-11 16:29 UTC, umangagrawal-crest commented on tests/test_discover.py
> +                # verify that all other fields have inclusion of available
```suggestion
                # verify that all other fields have inclusion of available metadata
```

2022-01-11 16:29 UTC, umangagrawal-crest commented on tests/test_discover.py
> +                # verify replication key(s)
```suggestion
                # verify replication key(s) match expectations
```

2022-01-11 16:29 UTC, umangagrawal-crest commented on tests/test_discover.py
> +
Add assertion comment
```suggestion
# verify that if there is a replication key we are doing INCREMENTAL otherwise FULL
```

2022-01-11 16:29 UTC, umangagrawal-crest commented on tests/test_discover.py
> +                                     expected_replication_keys, actual_replication_keys))
Add assertion for " Verify there are no duplicate metadata entries"
For reference: https://github.com/singer-io/tap-google-ads/blob/main/tests/test_google_ads_discovery.py#L102

2022-01-12 04:02 UTC, prijendev commented on tests/test_discover.py
> +                # Verify ensure the caatalog is found for a given stream
Updated.

2022-01-12 04:03 UTC, prijendev commented on tests/test_discover.py
> +                # verify that all other fields have inclusion of available
Updated

2022-01-12 04:03 UTC, prijendev commented on tests/test_discover.py
> +                # verify replication key(s)
Updated

2022-01-12 04:03 UTC, prijendev commented on tests/test_discover.py
> +
Added assertion comment

2022-01-12 04:03 UTC, prijendev commented on tests/test_discover.py
> +                                     expected_replication_keys, actual_replication_keys))
Added assertion.

2022-01-12 10:00 UTC, karanpanchal-crest commented on tests/test_all_fields.py
> +                #  BUG | below keys are not synced due to typo mismatch  https://jira.talendforge.org/browse/TDL-16481
Add comment of removing typo mismatch keys

2022-01-12 10:04 UTC, karanpanchal-crest requested changes
Resolve comments provided in the PR

2022-01-12 11:25 UTC, umangagrawal-crest approved these changes

2022-01-12 11:40 UTC, prijendev commented on tests/test_all_fields.py
> +                #  BUG | below keys are not synced due to typo mismatch  https://jira.talendforge.org/browse/TDL-16481
Added comment

2022-01-12 11:44 UTC, dbshah1212 approved these changes

2022-01-12 13:10 UTC, karanpanchal-crest approved these changes

2022-01-12 19:22 UTC, KrisPersonal commented on tap_activecampaign/schemas/automation_blocks.json
> +      ]
What is the purpose of this change?

2022-01-13 03:54 UTC, prijendev commented on tap_activecampaign/schemas/automation_blocks.json
> +      ]
In API response, the value of `param` field can be either object type or an empty array. The existing schema handles only object type values. So, here we have added support to the empty array value of the `param` field.
The possible value of `param` field:
1. "param": {"eventType": "never"}
2. "param": []

2022-01-13 15:56 UTC, KrisPersonal approved these changes

2022-01-13 18:42 UTC, kspeer825 requested changes
Base test suite looks great. One minor issue with the circle config

2022-01-17 07:54 UTC, prijendev commented on .circleci/config.yml
> +            - circleci-user
Added slack orb and tap-tester-user context

2022-01-18 12:05 UTC, kspeer825 requested changes

2022-01-18 12:05 UTC, kspeer825 commented on .circleci/config.yml
> +            - circleci-user
Can you please add the both contexts to the `build_daily` workflow too.

2022-01-18 12:27 UTC, prijendev commented on .circleci/config.yml
> +            - circleci-user
Added both contexts to the `build_daily` workflow.

2022-01-18 12:28 UTC, kspeer825 approved these changes
Thanks!

2022-01-18 12:34 UTC, merged