Fix the existing integration tests and add interrupt sync test case
singer-io/tap-activecampaign pull request #35
Opened 2023-03-21 06:13 UTC by sgandhi1311

# Description of change
Fix the existing integration tests and add interrupt sync test case

# Manual QA steps
 - Tested locally on dev-vm. Ran all the test cases.
 - Circle-Ci is passing.
 
# Risks
 - Low Risk
 
# Rollback steps
 - revert this branch

2023-03-21 06:34 UTC, kethan1122 requested changes

2023-03-21 06:34 UTC, kethan1122 commented on tests/test_all_fields.py
> +                    expected_all_keys = expected_all_keys - {'password_updated_utc_timestamp', 'cdate', 'udate'}
```suggestion
                expected_all_keys = expected_all_fields - self.MISSING_FIELDS.get(stream, set())
```
This looks bit dirty. you can define `MISSING_FIELDS` as dict with `key` as `stream name` and `value` as `set of missing fields`

2023-03-21 06:34 UTC, kethan1122 commented on tests/base.py
> +    def assertIsDateFormat(self, value, str_format):
this can be defined as static method. this isn't a blocker, just a suggestion

2023-03-21 06:34 UTC, kethan1122 commented on tests/test_bookmark.py
> +                    self.assertIsInstance(first_bookmark_value, str)
same assertions can be added for `second_bookmark_value` as well

2023-03-21 06:34 UTC, kethan1122 commented on tests/test_interrupted_sync.py
> +                        self.assertEqual(interrupted_record_count, full_sync_record_count,
for `full table` we can add an assertion to validate that we don't store the bookmark value
[refer this](https://github.com/stitchdata/tap-tester/blob/master/tap_tester/base_suite_tests/interrupted_sync_test.py#L207-L211)

2023-03-21 06:34 UTC, kethan1122 commented on tests/test_interrupted_sync.py
> +                        self.assertEqual(interrupted_record_count, full_sync_record_count,
Not just the count, we have to make sure that records are also same.
[refer this](https://github.com/stitchdata/tap-tester/blob/master/tap_tester/base_suite_tests/interrupted_sync_test.py#L215-L216)

2023-03-21 06:35 UTC, kethan1122 commented
please make sure you have all the assertions mentioned in [base suite](https://github.com/stitchdata/tap-tester/blob/master/tap_tester/base_suite_tests/interrupted_sync_test.py#L122) for interrupted sync

2023-03-21 12:51 UTC, rdeshmukh15 commented on tests/test_interrupted_sync.py
> +from dateutil import parser as parser
This import is unused.

2023-03-21 15:58 UTC, sgandhi1311 commented on tests/test_interrupted_sync.py
> +from dateutil import parser as parser
removed

2023-03-21 15:59 UTC, sgandhi1311 commented on tests/test_bookmark.py
> +                    self.assertIsInstance(first_bookmark_value, str)
done

2023-03-21 15:59 UTC, sgandhi1311 commented on tests/base.py
> +    def assertIsDateFormat(self, value, str_format):
done

2023-03-23 00:27 UTC, kethan1122 approved these changes

2023-03-23 04:10 UTC, rdeshmukh15 approved these changes

2023-03-23 09:55 UTC, merged