Fix the none type error exception when no records found
singer-io/tap-activecampaign pull request #37
Opened 2023-03-21 16:38 UTC by sgandhi1311

# Description of change
In a few cases, API sends the response - `{'contactData': [], 'meta': {'total': None}}` due to which the API total count gets assigned to None, and the following exception is raised - _TypeError: int() argument must be a string, a bytes-like object or a number, not 'NoneType'_
This PR fixes the above issue by assigning the value of the API total to 0 whenever the total is None.
Jira - [TDL-22422](https://jira.talendforge.org/browse/TDL-22422)

# Manual QA steps
 - Tested the sync locally.
 
# Risks
 - Low
 
# Rollback steps
 - revert this branch

2023-03-21 16:43 UTC, shantanu73 approved these changes

2023-03-21 17:09 UTC, luandy64 requested changes

2023-03-22 19:17 UTC, sgandhi1311 commented on tap_activecampaign/streams.py
> +
Agreed. Thanks for the detailed explanation. 
I have made the changes.

2023-03-23 12:48 UTC, luandy64 approved these changes

2023-03-23 15:01 UTC, merged