Initial commit for error handling
singer-io/tap-activecampaign pull request #8
Opened 2021-11-19 08:37 UTC by prijendev

# Description of change
- Updated error handling.
- Added default messages for each error code mentioned in [Document](https://developers.activecampaign.com/reference#errors) .
- Added unit test cases for the same.

# Manual QA steps
 - Raise error mentioned in the above document link and verify that it throws an error with proper message
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2022-01-05 04:51 UTC, prijendev commented on tap_activecampaign/transform.py
> -    fixed_records = fix_records(converted_json)
Fixed pylint error `assignment-from-no-return`. ([Reference](https://app.circleci.com/pipelines/github/singer-io/tap-activecampaign/551/workflows/e896a4c7-a0aa-4e56-9dd1-e1eb312518bb/jobs/555))

2022-01-11 11:41 UTC, dbshah1212 commented on tap_activecampaign/client.py
> +    if isinstance(exception, OSError) or isinstance(exception, Server5xxError) or isinstance(exception, Server429Error):
Are we retrying for every OSError? Do we need to specify any messages to retry?

2022-01-11 11:43 UTC, dbshah1212 commented on tap_activecampaign/client.py
> +    elif type(exception) == Exception and type(exception.args[0][1]) == ConnectionResetError:
Why we need to compare like: (exception.args[0][1]) == ConnectionResetError? can't we handle ConnectionResetError directly?

2022-01-11 11:45 UTC, dbshah1212 commented on tap_activecampaign/client.py
> +            exc = get_exception_for_status_code(status_code)
By this we will raise only the last exception, what about other exceptions?

2022-01-11 11:48 UTC, dbshah1212 commented on tap_activecampaign/client.py
> -        if response.status_code >= 500:
Where this will be handled? As in error code dict we have 500 only so what will happen for 502?

2022-01-11 11:57 UTC, prijendev commented on tap_activecampaign/client.py
> +    elif type(exception) == Exception and type(exception.args[0][1]) == ConnectionResetError:
I have noticed that tap sometimes throw `Exception: ConnectionResetError(104, 'Connection reset by peer')`. [Reference](https://app.circleci.com/pipelines/github/singer-io/tap-activecampaign/554/workflows/d448258e-20df-4e66-b2aa-bc8bd1f08912/jobs/558). So, only `ConnectionResetError` can't handle this error. That's why, I have handled this Exception explicitly.

2022-01-11 12:00 UTC, prijendev commented on tap_activecampaign/client.py
> +    if isinstance(exception, OSError) or isinstance(exception, Server5xxError) or isinstance(exception, Server429Error):
In the existing tap code, there is backoff available for `OSError`. So, I have not changed this part. [(Reference)](https://github.com/singer-io/tap-activecampaign/blob/master/tap_activecampaign/client.py#L132)

2022-01-11 12:04 UTC, prijendev commented on tap_activecampaign/client.py
> -        if response.status_code >= 500:
This is handled in `get_exception_for_status_code` function. [(Reference)](https://github.com/singer-io/tap-activecampaign/blob/TDL-16386-refactor-error-handling/tap_activecampaign/client.py#L94). It will retry all 5xx errors. Unit test case for 502 error is available.

2022-01-11 12:13 UTC, prijendev commented on tap_activecampaign/client.py
> +            exc = get_exception_for_status_code(status_code)
Basically, API returns the response that contains an `errors` object with multiple error titles for some of the errors. Here, it prepares an error message containing the title of all errors in the `errors` object and then raises the error with a prepared error message. Unit test case for this scenario available ([here](https://github.com/singer-io/tap-activecampaign/pull/8/files#diff-564f5a150a911874f076c69be2f66a98657624779b01c6598e1b31c913f87130R128))

2022-01-11 12:54 UTC, dbshah1212 commented on tap_activecampaign/client.py
> +            exc = get_exception_for_status_code(status_code)
Got it but I think we can place this line outside the for loop.

2022-01-11 13:18 UTC, prijendev commented on tap_activecampaign/client.py
> +            exc = get_exception_for_status_code(status_code)
Updated.

2022-01-11 13:24 UTC, dbshah1212 approved these changes

2022-01-12 10:18 UTC, karanpanchal-crest requested changes
Resolve provided comments

2022-01-12 12:51 UTC, karanpanchal-crest approved these changes

2022-01-12 19:20 UTC, KrisPersonal approved these changes

2022-01-13 18:47 UTC, kspeer825 approved these changes
I left a suggestion on the unittests pattern.

2022-01-13 18:47 UTC, kspeer825 commented on tests/unittests/test_error_handling.py
> +            self.assertEqual(str(e), expected_error_message)
I think there is a flaw in this pattern. I the mocked client does not throw an error this would not execute the assertion inside the `except` and we would get False Positives.

2022-01-17 06:48 UTC, merged