Updated dict based to class based
singer-io/tap-activecampaign pull request #9
Opened 2021-11-25 10:31 UTC by prijendev

# Description of change
- Converted dictionary of each stream to a class
- Reshuffled sync code from sync.py to `ActiveCampaign` class in the stream.py
- Verified that there is no difference in catalog and state file of older dict based code and newer code.
- Pass the integration test case in local.

# Manual QA steps
 - Clone old code and newer code in local.
 - Run discover mode and compare catalog.
 - Run sync mode and verify output.
 
# Risks
 - 
 
# Rollback steps
 - revert this branch

2021-12-15 06:05 UTC, NevilParikh14 commented on tap_activecampaign/streams.py
> +    'ecommerce_order_products'
@prijendev can't we use "parent": "child" format here for the ease to know the parent stream of the mentioned sub-stream?

2021-12-15 10:00 UTC, prijendev commented on tap_activecampaign/streams.py
> +    'ecommerce_order_products'
Updated.

2022-01-12 09:08 UTC, karanpanchal-crest commented on .circleci/config.yml
> +          name: 'JSON Validator'
Add comment of code change

2022-01-12 09:12 UTC, karanpanchal-crest commented on tap_activecampaign/streams.py
> +import singer
@prijendev Please add detailed comments in all the functions

2022-01-12 09:14 UTC, karanpanchal-crest commented on tap_activecampaign/streams.py
> +            LOGGER.error('OS Error writing record for: {}'.format(stream_name))
```suggestion
            LOGGER.error('OS Error while writing record for: {}'.format(stream_name))
```

2022-01-12 09:15 UTC, karanpanchal-crest commented on tap_activecampaign/streams.py
> +            LOGGER.error('Type Error writing record for: {}'.format(stream_name))
```suggestion
            LOGGER.error('Type Error while writing record for: {}'.format(stream_name))
```

2022-01-12 09:26 UTC, karanpanchal-crest commented on tap_activecampaign/streams.py
> +            return max_bookmark_value, counter.value
Add space

2022-01-12 09:48 UTC, karanpanchal-crest approved these changes

2022-01-12 09:49 UTC, karanpanchal-crest requested changes
Incorporate requested changes in the PR

2022-01-12 12:18 UTC, prijendev commented on tap_activecampaign/streams.py
> +            LOGGER.error('OS Error writing record for: {}'.format(stream_name))
Updated

2022-01-12 12:18 UTC, prijendev commented on tap_activecampaign/streams.py
> +            LOGGER.error('Type Error writing record for: {}'.format(stream_name))
Updated

2022-01-12 12:19 UTC, prijendev commented on tap_activecampaign/streams.py
> +            return max_bookmark_value, counter.value
Added space

2022-01-12 12:21 UTC, prijendev commented on tap_activecampaign/streams.py
> +import singer
Added comments in all the functions

2022-01-12 12:30 UTC, prijendev commented on .circleci/config.yml
> +          name: 'JSON Validator'
Here, `JSON Validator` and `pylint` are added in the `config.yml`.  Removed the integration test case from config.yml as no tests are available in this PR which caused build failures. The existing test case was related to tap-Snapchat. So, we removed that and there are no other test cases available regarding this tap-activecampaign code.

2022-01-12 12:36 UTC, dbshah1212 approved these changes

2022-01-12 12:42 UTC, karanpanchal-crest commented on .circleci/config.yml
> +          name: 'JSON Validator'
Also, standard test cases are added as part of PR #11

2022-01-12 12:46 UTC, karanpanchal-crest requested changes

2022-01-12 12:46 UTC, karanpanchal-crest commented on tap_activecampaign/streams.py
> +                    else:
@prijendev Please add comments above the `if-else` condition

2022-01-12 12:46 UTC, karanpanchal-crest commented on tap_activecampaign/streams.py
> +            # LOGGER.info('transformed_data = {}'.format(transformed_data)) # TESTING, comment out
@prijendev please remove this commented code

2022-01-12 13:04 UTC, prijendev commented on tap_activecampaign/streams.py
> +                    else:
Added comments

2022-01-12 13:04 UTC, prijendev commented on tap_activecampaign/streams.py
> +            # LOGGER.info('transformed_data = {}'.format(transformed_data)) # TESTING, comment out
Removed

2022-01-12 13:12 UTC, karanpanchal-crest approved these changes

2022-01-12 19:16 UTC, KrisPersonal commented on tap_activecampaign/streams.py
> +    def process_records(self,
Add some comments for process_records. What is this function is expected to do?

2022-01-13 06:06 UTC, prijendev commented on tap_activecampaign/streams.py
> +    def process_records(self,
Added comments in the code.

2022-01-13 15:55 UTC, KrisPersonal approved these changes

2022-01-13 19:39 UTC, kspeer825 approved these changes
Approved, but I think the base suite should get merged prior to this PR.

2022-01-17 07:04 UTC, merged